import sys
from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtWidgets import QLineEdit
from login import Register, CheckValidation
from login import LogIn
from main3 import ToDoWindow

class RegisterWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(599, 500)
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("imagess/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                MainWindow.setWindowIcon(icon)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit.setGeometry(QtCore.QRect(130, 160, 191, 20))
                self.lineEdit.setObjectName("lineEdit")
                self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit_2.setGeometry(QtCore.QRect(130, 220, 191, 20))
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit_3.setGeometry(QtCore.QRect(130, 274, 191, 20))
                self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
                self.lineEdit_3.setObjectName("lineEdit_3")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(70, 140, 61, 16))
                self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(70, 210, 47, 13))
                self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(70, 260, 60, 16))
                self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_3.setObjectName("label_3")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(70, 80, 291, 31))
                font = QtGui.QFont()
                font.setFamily("UTM Avo")
                font.setPointSize(15)
                self.label_5.setFont(font)
                self.label_5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(70, 40, 181, 41))
                font = QtGui.QFont()
                font.setFamily("Tw Cen MT Condensed")
                font.setPointSize(35)
                font.setBold(True)
                font.setWeight(75)
                self.label_6.setFont(font)
                self.label_6.setStyleSheet("color: #063a52")
                self.label_6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_6.setObjectName("label_6")
                
                self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
                self.commandLinkButton.setGeometry(QtCore.QRect(70, 380, 110, 31))
                font = QtGui.QFont()
                font.setFamily("UTM Avo")
                font.setPointSize(9)
                font.setItalic(True)
                font.setUnderline(True)
                self.commandLinkButton.setFont(font)
                self.commandLinkButton.setStyleSheet("color: #063a52")
                self.commandLinkButton.setIconSize(QtCore.QSize(0, 0))
                self.commandLinkButton.setAutoRepeatDelay(297)
                self.commandLinkButton.setObjectName("commandLinkButton")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(130, 290, 181, 31))
                font = QtGui.QFont()
                font.setPointSize(7)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color:gray")
                self.label_4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_4.setObjectName("label_4")
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(130, 180, 181, 22))
                font = QtGui.QFont()
                font.setPointSize(7)
                self.label_8.setFont(font)
                self.label_8.setStyleSheet("color:gray")
                self.label_8.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_8.setObjectName("label_8")
                self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
                self.checkBox.setGeometry(QtCore.QRect(70, 350, 111, 17))
                self.checkBox.setTristate(False)
                self.checkBox.setObjectName("checkBox")
                self.checkBox.stateChanged.connect(self.show_pass)
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(400, 140, 121, 121))
                self.label_9.setText("")
                self.label_9.setPixmap(QtGui.QPixmap("imagess/register.png"))
                self.label_9.setScaledContents(True)
                self.label_9.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_9.setObjectName("label_9")
                self.label_10 = QtWidgets.QLabel(self.centralwidget)
                self.label_10.setGeometry(QtCore.QRect(390, 250, 141, 51))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(10)
                font.setBold(False)
                font.setItalic(True)
                font.setWeight(50)
                self.label_10.setFont(font)
                self.label_10.setAlignment(QtCore.Qt.AlignCenter)
                self.label_10.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_10.setObjectName("label_10")
                self.label_11 = QtWidgets.QLabel(self.centralwidget)
                self.label_11.setGeometry(QtCore.QRect(230, 135, 91, 31))
                font = QtGui.QFont()
                font.setPointSize(7)
                font.setItalic(True)
                self.label_11.setFont(font)
                self.label_11.setStyleSheet("color: red")
                self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.label_11.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_11.setObjectName("label_11")
                self.label_12 = QtWidgets.QLabel(self.centralwidget)
                self.label_12.setGeometry(QtCore.QRect(230, 195, 91, 31))
                font = QtGui.QFont()
                font.setPointSize(7)
                font.setItalic(True)
                self.label_12.setFont(font)
                self.label_12.setStyleSheet("color: red")
                self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.label_12.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_12.setObjectName("label_12")
                self.label_13 = QtWidgets.QLabel(self.centralwidget)
                self.label_13.setGeometry(QtCore.QRect(230, 255, 91, 21))
                font = QtGui.QFont()
                font.setPointSize(7)
                font.setItalic(True)
                self.label_13.setFont(font)
                self.label_13.setStyleSheet("color: red")
                self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.label_13.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_13.setObjectName("label_13")
                self.label_14 = QtWidgets.QLabel(self.centralwidget)
                self.label_14.setGeometry(QtCore.QRect(70, 320, 70, 17))
                font = QtGui.QFont()
                font.setPointSize(8)
                font.setItalic(True)
                self.label_14.setFont(font)
                self.label_14.setStyleSheet("color:gray")
                self.label_14.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_14.setObjectName("label_14")
                
                self.label_15 = QtWidgets.QLabel(self.centralwidget)
                self.label_15.setGeometry(QtCore.QRect(70, 120, 191, 16))
                font = QtGui.QFont()
                font.setPointSize(8)
                font.setItalic(True)
                self.label_15.setFont(font)
                self.label_15.setStyleSheet("color:red")
                self.label_15.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_15.setObjectName("label_15")
                
                self.label_16 = QtWidgets.QLabel(self.centralwidget)
                self.label_16.setGeometry(QtCore.QRect(70, 120, 300, 16))
                font = QtGui.QFont()
                font.setPointSize(8)
                font.setItalic(False)
                self.label_16.setFont(font)
                self.label_16.setStyleSheet("color:blue")
                self.label_16.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_16.setObjectName("label_15")
                
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(280, 380, 71, 31))
                font = QtGui.QFont()
                font.setFamily("UTM Avo")
                font.setPointSize(11)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton.setFont(font)
                self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.pushButton.setStyleSheet("background-color : #063a52; color: white\n"
                "")
                self.pushButton.setAutoDefault(True)
                self.pushButton.setObjectName("pushButton")
                self.pushButton.clicked.connect(self.register)

                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 21))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)
                
        def register(self):
                username = self.lineEdit.text()
                email = self.lineEdit_2.text()
                password = self.lineEdit_3.text()
                check_name, check_email, check_pass = Register().check_infor(username, email, password)
                check_existed = CheckValidation(username, email, password).existed_account()
  
                if check_name == "empty":
                        self.label_11.setText("enter username ")
                elif check_name == "existed":
                        self.label_11.setText("existed! ")
                elif check_name == "tooshort":
                        self.label_11.setText("too short! ")
                else:
                        self.label_11.clear()

                if check_email == False:
                        self.label_12.setText("invalid! ")
                elif check_email == "empty":
                        self.label_12.setText("enter email ")
                elif check_email == "existed":
                        self.label_12.setText("existed! ")
                else:
                        self.label_12.clear()
                        
                if check_pass == False:
                        self.label_13.setText("invalid! ")
                elif check_email == "empty":
                        self.label_13.setText("enter password ")
                # else:
                #         self.label_13.clear()
                        
                if check_existed == False:
                        self.label_15.setText("The account is existed. Sign in instead. ")
                        self.label_13.clear()
                        self.label_12.clear()
                        self.label_11.clear()
                else:
                        self.label_15.clear()
                        
                if check_email==True and check_name==True and check_pass==True and check_existed != False:
                        self.label_16.setText("Create account successfully. Sign in to continue. ")
                        Register().add_account(username, email, password)

        
        def show_pass(self):
                if self.checkBox.isChecked():
                        self.lineEdit_3.setEchoMode(QLineEdit.Normal)
                else:
                        self.lineEdit_3.setEchoMode(QLineEdit.Password)
        
        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "ToDo List - Register"))
                self.label.setText(_translate("MainWindow", "Username(*)"))
                self.label_2.setText(_translate("MainWindow", "Email(*)"))
                self.label_3.setText(_translate("MainWindow", "Password(*)"))
                self.label_5.setText(_translate("MainWindow", "Create your ToDo account"))
                self.label_6.setText(_translate("MainWindow", "ToDo List"))
                self.commandLinkButton.setText(_translate("MainWindow", "Sign in instead "))
                self.commandLinkButton.clicked.connect(self.open_login)
                self.commandLinkButton.clicked.connect(self.hide_register)
                self.label_4.setText(_translate("MainWindow", "Password must include number and \n"
                "uppercase letter"))
                self.label_8.setText(_translate("MainWindow", "You can use numbers, letters & symbols.\nIt must contains at least 4 characters"))
                self.checkBox.setText(_translate("MainWindow", "show password?"))
                self.label_10.setText(_translate("MainWindow", "One account.\n"
                "All planning for you."))
                self.label_14.setText(_translate("MainWindow", "(*): required "))
                self.pushButton.setText(_translate("MainWindow", "Create "))
        
        def open_login(self):
                self.window = QtWidgets.QMainWindow()
                self.ui = LogInWindow()
                self.ui.setupUi(self.window)
                self.window.show()
                
        def hide_register(self):
                MainWindow.hide() 
                
                
class LogInWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(800, 600)
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                MainWindow.setFont(font)
                MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("imagess/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                MainWindow.setWindowIcon(icon)
                MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
                MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(320, 200, 171, 51)) 
                font = QtGui.QFont()
                font.setFamily("Market Deco")
                font.setPointSize(26)
                self.label.setFont(font)
                self.label.setAlignment(QtCore.Qt.AlignCenter)
                self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(320, 250, 171, 21))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.label_2.setFont(font)
                self.label_2.setTextFormat(QtCore.Qt.RichText)
                self.label_2.setAlignment(QtCore.Qt.AlignCenter)
                self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(230, 320, 47, 13))
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(230, 350, 47, 13))
                self.label_4.setObjectName("label_4")
                self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit.setGeometry(QtCore.QRect(290, 310, 241, 20))
                self.lineEdit.setObjectName("lineEdit")
                self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
                self.lineEdit_2.setGeometry(QtCore.QRect(290, 340, 241, 20))
                self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(300, 446, 151, 20))
                font = QtGui.QFont()
                font.setPointSize(8)
                font.setItalic(True)
                font.setKerning(False)
                self.label_5.setFont(font)
                self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
                self.label_5.setObjectName("label_5")
                self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
                self.commandLinkButton.setGeometry(QtCore.QRect(440, 440, 81, 31))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(8)
                font.setItalic(True)
                font.setUnderline(True)
                self.commandLinkButton.setFont(font)
                self.commandLinkButton.setIconSize(QtCore.QSize(12, 12))
                self.commandLinkButton.setAutoRepeatDelay(297)
                self.commandLinkButton.setObjectName("commandLinkButton")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(330, 60, 151, 161))
                self.label_6.setText("")
                self.label_6.setPixmap(QtGui.QPixmap("imagess/welcome.png"))
                self.label_6.setScaledContents(True)
                self.label_6.setObjectName("label_6")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(370, 400, 75, 21))
                self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
                self.checkBox.setGeometry(QtCore.QRect(290, 370, 111, 17))
                self.checkBox.setTristate(False)
                self.checkBox.setObjectName("checkBox")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(290, 290, 241, 20))
                self.label_7.setObjectName("label_7")
                self.label_7.setStyleSheet("color: red")

                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setBold(True)
                font.setItalic(False)
                font.setUnderline(False)
                font.setWeight(75)
                font.setStrikeOut(False)
                self.pushButton.setFont(font)
                self.pushButton.setMouseTracking(True)
                self.pushButton.setTabletTracking(True)
                self.pushButton.setCheckable(False)
                self.pushButton.setObjectName("pushButton")
                MainWindow.setCentralWidget(self.centralwidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "ToDo List - LogIn"))
                self.label.setText(_translate("MainWindow", "WELCOME!"))
                self.label.setStyleSheet("color:#063a52")
                self.label_2.setText(_translate("MainWindow", "Log In to plan your day"))
                self.label_3.setText(_translate("MainWindow", "Username"))
                self.label_4.setText(_translate("MainWindow", "Password"))
                self.label_5.setText(_translate("MainWindow", "Haven't got an account?"))
                self.commandLinkButton.setText(_translate("MainWindow", "Register"))
                self.pushButton.setText(_translate("MainWindow", "Enter"))
                self.pushButton.clicked.connect(self.login)
                self.commandLinkButton.clicked.connect(self.open_register)
                self.commandLinkButton.clicked.connect(self.hide_login)    
                self.checkBox.setText("show password?")
                self.checkBox.stateChanged.connect(self.show_pass)           

        def login(self):
                username = self.lineEdit.text()
                password = self.lineEdit_2.text()
                log = LogIn(username, password).login()
                if log != True:
                        self.label_7.setText("Invalid usename or password, retry!")
                elif len(username) == 0 and len(password) == 0:
                        self.label_7.setText("Please fill in username and password")
                else:
                        self.win2 = ToDoWindow()
                        self.win2.show()
        
        def open_register(self):
                self.window = QtWidgets.QMainWindow()
                self.ui = RegisterWindow()
                self.ui.setupUi(self.window)
                self.window.show()
        
        def hide_login(self):
                MainWindow.hide() 
                
                
        def show_pass(self):
                if self.checkBox.isChecked():
                        self.lineEdit_2.setEchoMode(QLineEdit.Normal)
                else:
                        self.lineEdit_2.setEchoMode(QLineEdit.Password)
                
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LogInWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())